import "./globals.css";

import localFont from "next/font/local";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const adventures = localFont({
  src: [
    {
      path: "./fonts/adventures/AdventuresUnlimited-ScriptBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/adventures/AdventuresUnlimited-ScriptRg.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: '--font-adventures',
});
const brandon = localFont({
  src: [
    {
      path: "./fonts/brandon/Brandon_bld_it.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_bld.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/brandon/Brandon_blk_it.otf",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_blk.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/brandon/Brandon_light_it.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/brandon/Brandon_med_it.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_med.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/brandon/Brandon_reg_it.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_reg.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/brandon/Brandon_thin_it.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/brandon/Brandon_thin.otf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: '--font-brandon',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={` ${brandon.variable} ${adventures.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
